config/routes.rb
Rails.application.routes.draw do
  resources :rooms, except: [:show]
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  beds        :integer
#  guests      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_url   :string
#

class Room < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
     @room = Room.find(params[:id])
    end

    def edit
     @room = Room.find(params[:id])
    end

    def update
     @room = Room.find(params[:id])
     if @room.update(room_params)
       redirect_to rooms_path
     else
       render :edit
     end
    end

     def destroy
       room = Room.find(params[:id])
       room.destroy

      redirect_to rooms_path
     end

  protected
    def room_params
      params.require(:room).permit(:title, :description, :beds, :guests, :image_url, :price_per_night)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rooms</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">AireCyD</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Habitaciones", rooms_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>

app/views/rooms/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= @room.new_record? ? "Publicar": "Editar" %> Habitación</h1>

      <%= form_for @room do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: 'form-control input-lg', placeholder: "Título" %>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: 'form-control input-lg', placeholder: "Descripción" %>
        </div>

        <div class="form-group">
          <%= f.label :beds, "Número de Camas" %>
          <%= f.number_field :beds, class: 'form-control input-lg col-sm-2' %>
        </div>

        <div class="form-group">
          <%= f.label :guests, "Número de Huéspedes" %>
          <%= f.number_field :guests, class: 'form-control input-lg' %>
        </div>

        <div class="form-group">
          <%= f.text_field :image_url, class: 'form-control input-lg', placeholder: "URL de Imagen" %>
        </div>

        <div class="form-group">
            <%= f.label :price_per_nigh, "Precio por noche" %>
          <%= f.text_field :price_per_night, class: 'form-control input-lg', placeholder: "Precio por noche" %>
        </div>

        <div class="actions text-right">
          <%= f.submit @room.new_record? ? "Crear Habitación" : "Editar Habitación", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<%= form_for @room, url: room_path(@room), method: :put do |f| %>
<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>

<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>

<div>
    <%= f.label :beds %>
    <%= f.text_area :beds %>
</div>

<div>
    <%= f.label :guests %>
    <%= f.text_area :guests %>
</div>

<div>
    <%= f.label :image_url %>
    <%= f.text_area :image_url %>
</div>

<div>
    <%= f.label :price_per_night %>
    <%= f.text_area :price_per_night %>
</div>

<div>
   <%= f.submit %>
</div>

<% end %>

app/views/rooms/index.html.erb
<div class="container rooms">
  <div class="row">
    <div class="col-sm-12">
      <header>
        <h1>Habitaciones</h1>
        <%= link_to "<span class='glyphicon glyphicon-plus'></span><span class='hidden-xs'> Publicar </span>  Habitación".html_safe, new_room_path, class: "btn btn-primary new-room" %>
      </header>

      <div class="rooms-list">
      <% @rooms.each do |room| %>
        <div class="room">
          <div class="row">
            <div class="col-sm-5 col-md-4"><img src="<%= room.image_url %>"></div>
            <div class="col-sm-7 col-md-8">
              <div class="details clearfix">
                <h3><%= room.title %></h3>
                <div class="description"><%= room.description.truncate(255) if room.description %></div>
                <div class="number">
                  <div class="number-value"><%= room.beds %></div>
                  <div class="number-label">Camas</div>
                </div>
                <div class="number">
                  <div class="number-value"><%= room.guests %></div>
                  <div class="number-label">Huéspedes</div>
                </div>
                <div class="actions">
                  <%= link_to "<span class='glyphicon glyphicon-pencil'><span>".html_safe, edit_room_path(room), class: "edit-room-btn" %>
                  <%= link_to "<span class='glyphicon glyphicon-trash'><span>".html_safe, room, method: :delete, data: { confirm: "¿Estás seguro de eliminar esta habitación?" }, class: "destroy-room-btn" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<h1>Detalles del blog <%= @room.id %></h1>

<div class=""> Title: <%= @room.title %></div>
<div class=""> Content: <%= @room.content %></div>

<%= link_to "Ir a las habitaciones", room_index_path %>